name: Daily Crypto Notify

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 23 * * *' # UTC 23点触发，东八区为早上7点

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run main.py
        env:
          WEBHOOK_NEWCOINS: ${{ secrets.WEBHOOK_NEWCOINS }}
        run: python main.py
